### ISSUE TITLE
Error: List of numpy arrays passed is not the size of what the model is expecting

### ISSUE THREAD

**Issue by Trotts** [matheushent/score-cam#2] opened 2020-04-28 11:05 UTC
Hi, 

Thank you for writing and maintaining this repo, it's a very easy to understand implementation of Score-CAM! 

I have the VGG16 example working  fine, and am now trying to adapt this to use my own Mask-RCNN model I have developed using [this repo](https://github.com/matterport/Mask_RCNN) as a basis. I am running into an error however that I am unsure of how to fix, and was wondering if any advice could be provided?

When running 

```
explainer = ScoreCAM()

target_size = (3456, 5184)

data = (img, None)
# Compute ScoreCAM on VGG16
image = explainer.explain(
    data, model.keras_model, max_prob, target_size, _grid=False
)[0]
explainer.save(image, ".", "score_cam.png")
```

I am running into the following error:

```
ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 3 array(s), but instead got the following list of 1 arrays: [<tf.Tensor: id=10530, shape=(64, 3456, 5184, 3), dtype=float32, numpy=
array([[[[ 3.64952057e+02,  3.75305298e+02,  3.77893616e+02],
         [ 1.37095261e+02,  1.40957092e+02,  1.41922562e+02],

```

The full stack trace can be seen [here](https://pastebin.com/M0bSvDGA). I *think* the issue is that masked_images is not in the form it should be? A printout of masked_images can be seen [here](https://pastebin.com/PYLHTv4M).

Any help is greatly appreciated!

**Comment by matheushent** [comment] 2020-04-28 11:54
Hello @Trotts,

I guess the problem is your model requires multiple inputs, while this implementation is designed to support a simple CNN model for 1 input of size (batch_size, H, W, 3).

**Comment by Trotts** [comment] 2020-04-29 15:23
Hi @matheushent, thank you for the reply. My model takes three inputs, the image, some image meta-data, and some anchors, as seen below:

```
print(model.keras_model.inputs) 

[<tf.Tensor 'input_image:0' shape=(?, ?, ?, 3) dtype=float32>, <tf.Tensor 'input_image_meta:0' shape=(?, 14) dtype=float32>, <tf.Tensor 'input_anchors:0' shape=(?, ?, 4) dtype=float32>] <class 'list'>

print(model.keras_model.outputs)

[<tf.Tensor 'mrcnn_detection/Identity:0' shape=(1, 100, 6) dtype=float32>, <tf.Tensor 'mrcnn_class/Identity:0' shape=(?, ?, 2) dtype=float32>, <tf.Tensor 'mrcnn_bbox/Identity:0' shape=(?, ?, 2, 4) dtype=float32>, <tf.Tensor 'mrcnn_mask/Identity:0' shape=(1, 100, 28, 28, 2) dtype=float32>, <tf.Tensor 'ROI/Identity:0' shape=(1, ?, 4) dtype=float32>, <tf.Tensor 'rpn_class/Identity:0' shape=(?, ?, 2) dtype=float32>, <tf.Tensor 'rpn_bbox/Identity:0' shape=(?, ?, 4) dtype=float32>] <class 'list'>


```

Using the VGG16 code as an example, it seems as though I only need the mrcnn_class output, as this gives the class ID. 

I have been trying to adapt the score-cam code to work with multiple inputs, however am struggling with memory issues which makes me think I am doing something wrong. These issues occur specifically when generating the classes_activation_scale using the softmax model. My previous error was fixed by passing the softmax model all inputs it required, however it seems to use up massive amounts of memory to calculate the classes_activation_scale, and eventually I run out. Note my image sizes passed to my model are required to be very large, at (3456, 5184).

Do you have any suggestions as to how this could be fixed?

My code can be found [here](https://pastebin.com/eLP4ZX5q).

**Comment by matheushent** [comment] 2020-04-29 15:33
@Trotts I guess the only way to run on a computer with more memory. Try to run on a google cloud instance with NVIDIA Tesla V100. All my code was run on NVIDIA RTX 2070 8 GB DDR8, and even so, I faced some memory errors. Note the image size is 224x224, so running with 3456x5184 requires a lot of memory.

I'm closing the issue since the original problem is solved. Feel free to contact me by e-mail for other problems.

e-mail: matheustosta66@gmail.com

**Closed by matheushent** 2020-04-29 15:33 UTC
